"""Reviews

Revision ID: 2e6381e0d1c6
Revises: 7ac1b1f825b9
Create Date: 2024-05-27 04:33:58.237651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e6381e0d1c6'
down_revision: Union[str, None] = '7ac1b1f825b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('characteristic_component_id_fkey', 'characteristic', type_='foreignkey')
    op.create_foreign_key(None, 'characteristic', 'component', ['component_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characteristic', type_='foreignkey')
    op.create_foreign_key('characteristic_component_id_fkey', 'characteristic', 'component', ['component_id'], ['id'])
    op.drop_table('review')
    # ### end Alembic commands ###
