"""Initial

Revision ID: 7568a07995b4
Revises: 
Create Date: 2024-03-18 01:17:01.114903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7568a07995b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_gaming', sa.Boolean(), nullable=True),
    sa.Column('cpu_id', sa.Integer(), nullable=False),
    sa.Column('gpu_id', sa.Integer(), nullable=False),
    sa.Column('ram_id', sa.Integer(), nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.Column('motherboard_id', sa.Integer(), nullable=False),
    sa.Column('power_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PC')
    # ### end Alembic commands ###
