"""test2

Revision ID: 04f632bc0984
Revises: f939325d29e4
Create Date: 2024-04-17 00:06:29.627812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f632bc0984'
down_revision: Union[str, None] = 'f939325d29e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characteristic', 'component_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user_pc', sa.Column('cpu_id', sa.Integer(), nullable=False))
    op.add_column('user_pc', sa.Column('gpu_id', sa.Integer(), nullable=False))
    op.add_column('user_pc', sa.Column('mb_id', sa.Integer(), nullable=False))
    op.add_column('user_pc', sa.Column('ram_id', sa.Integer(), nullable=False))
    op.add_column('user_pc', sa.Column('memory_id', sa.Integer(), nullable=False))
    op.add_column('user_pc', sa.Column('power_id', sa.Integer(), nullable=False))
    op.add_column('user_pc', sa.Column('cooler_id', sa.Integer(), nullable=False))
    op.add_column('user_pc', sa.Column('case_id', sa.Integer(), nullable=False))
    op.alter_column('user_pc', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('user_pc_power_fkey', 'user_pc', type_='foreignkey')
    op.drop_constraint('user_pc_cooler_fkey', 'user_pc', type_='foreignkey')
    op.drop_constraint('user_pc_gpu_fkey', 'user_pc', type_='foreignkey')
    op.drop_constraint('user_pc_cpu_fkey', 'user_pc', type_='foreignkey')
    op.drop_constraint('user_pc_case_fkey', 'user_pc', type_='foreignkey')
    op.drop_constraint('user_pc_ram_fkey', 'user_pc', type_='foreignkey')
    op.drop_constraint('user_pc_memory_fkey', 'user_pc', type_='foreignkey')
    op.drop_constraint('user_pc_mb_fkey', 'user_pc', type_='foreignkey')
    op.create_foreign_key(None, 'user_pc', 'component', ['power_id'], ['id'])
    op.create_foreign_key(None, 'user_pc', 'component', ['cpu_id'], ['id'])
    op.create_foreign_key(None, 'user_pc', 'component', ['case_id'], ['id'])
    op.create_foreign_key(None, 'user_pc', 'component', ['gpu_id'], ['id'])
    op.create_foreign_key(None, 'user_pc', 'component', ['ram_id'], ['id'])
    op.create_foreign_key(None, 'user_pc', 'component', ['memory_id'], ['id'])
    op.create_foreign_key(None, 'user_pc', 'component', ['cooler_id'], ['id'])
    op.create_foreign_key(None, 'user_pc', 'component', ['mb_id'], ['id'])
    op.drop_column('user_pc', 'gpu')
    op.drop_column('user_pc', 'ram')
    op.drop_column('user_pc', 'cooler')
    op.drop_column('user_pc', 'mb')
    op.drop_column('user_pc', 'cpu')
    op.drop_column('user_pc', 'case')
    op.drop_column('user_pc', 'memory')
    op.drop_column('user_pc', 'power')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_pc', sa.Column('power', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_pc', sa.Column('memory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_pc', sa.Column('case', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_pc', sa.Column('cpu', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_pc', sa.Column('mb', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_pc', sa.Column('cooler', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_pc', sa.Column('ram', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_pc', sa.Column('gpu', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_pc', type_='foreignkey')
    op.drop_constraint(None, 'user_pc', type_='foreignkey')
    op.drop_constraint(None, 'user_pc', type_='foreignkey')
    op.drop_constraint(None, 'user_pc', type_='foreignkey')
    op.drop_constraint(None, 'user_pc', type_='foreignkey')
    op.drop_constraint(None, 'user_pc', type_='foreignkey')
    op.drop_constraint(None, 'user_pc', type_='foreignkey')
    op.drop_constraint(None, 'user_pc', type_='foreignkey')
    op.create_foreign_key('user_pc_mb_fkey', 'user_pc', 'component', ['mb'], ['id'])
    op.create_foreign_key('user_pc_memory_fkey', 'user_pc', 'component', ['memory'], ['id'])
    op.create_foreign_key('user_pc_ram_fkey', 'user_pc', 'component', ['ram'], ['id'])
    op.create_foreign_key('user_pc_case_fkey', 'user_pc', 'component', ['case'], ['id'])
    op.create_foreign_key('user_pc_cpu_fkey', 'user_pc', 'component', ['cpu'], ['id'])
    op.create_foreign_key('user_pc_gpu_fkey', 'user_pc', 'component', ['gpu'], ['id'])
    op.create_foreign_key('user_pc_cooler_fkey', 'user_pc', 'component', ['cooler'], ['id'])
    op.create_foreign_key('user_pc_power_fkey', 'user_pc', 'component', ['power'], ['id'])
    op.alter_column('user_pc', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('user_pc', 'case_id')
    op.drop_column('user_pc', 'cooler_id')
    op.drop_column('user_pc', 'power_id')
    op.drop_column('user_pc', 'memory_id')
    op.drop_column('user_pc', 'ram_id')
    op.drop_column('user_pc', 'mb_id')
    op.drop_column('user_pc', 'gpu_id')
    op.drop_column('user_pc', 'cpu_id')
    op.alter_column('characteristic', 'component_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
