"""Таблица характеристик комплектующих

Revision ID: 1fbb2f8be5fe
Revises: 9112e618d726
Create Date: 2024-04-16 14:56:38.072258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fbb2f8be5fe'
down_revision: Union[str, None] = '9112e618d726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characteristic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('attribute', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('component', sa.Column('description', sa.String(), nullable=True))
    op.add_column('component', sa.Column('price', sa.String(), nullable=False))
    op.drop_column('component', 'descrition')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('component', sa.Column('descrition', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('component', 'price')
    op.drop_column('component', 'description')
    op.drop_table('characteristic')
    # ### end Alembic commands ###
