"""ReadyPc

Revision ID: 42dd5d0d9c94
Revises: 04f632bc0984
Create Date: 2024-04-18 00:49:22.336315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42dd5d0d9c94'
down_revision: Union[str, None] = '04f632bc0984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ready_pc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ready_pc_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ready_pc_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.ForeignKeyConstraint(['ready_pc_id'], ['ready_pc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_pc_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_pc_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.ForeignKeyConstraint(['user_pc_id'], ['user_pc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user_pc', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('user_pc_memory_id_fkey', 'user_pc', type_='foreignkey')
    op.drop_constraint('user_pc_power_id_fkey', 'user_pc', type_='foreignkey')
    op.drop_constraint('user_pc_cpu_id_fkey', 'user_pc', type_='foreignkey')
    op.drop_constraint('user_pc_gpu_id_fkey', 'user_pc', type_='foreignkey')
    op.drop_constraint('user_pc_case_id_fkey', 'user_pc', type_='foreignkey')
    op.drop_constraint('user_pc_cooler_id_fkey', 'user_pc', type_='foreignkey')
    op.drop_constraint('user_pc_mb_id_fkey', 'user_pc', type_='foreignkey')
    op.drop_constraint('user_pc_ram_id_fkey', 'user_pc', type_='foreignkey')
    op.drop_column('user_pc', 'memory_id')
    op.drop_column('user_pc', 'ram_id')
    op.drop_column('user_pc', 'cpu_id')
    op.drop_column('user_pc', 'power_id')
    op.drop_column('user_pc', 'mb_id')
    op.drop_column('user_pc', 'gpu_id')
    op.drop_column('user_pc', 'cooler_id')
    op.drop_column('user_pc', 'case_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_pc', sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_pc', sa.Column('cooler_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_pc', sa.Column('gpu_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_pc', sa.Column('mb_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_pc', sa.Column('power_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_pc', sa.Column('cpu_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_pc', sa.Column('ram_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_pc', sa.Column('memory_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_pc_ram_id_fkey', 'user_pc', 'component', ['ram_id'], ['id'])
    op.create_foreign_key('user_pc_mb_id_fkey', 'user_pc', 'component', ['mb_id'], ['id'])
    op.create_foreign_key('user_pc_cooler_id_fkey', 'user_pc', 'component', ['cooler_id'], ['id'])
    op.create_foreign_key('user_pc_case_id_fkey', 'user_pc', 'component', ['case_id'], ['id'])
    op.create_foreign_key('user_pc_gpu_id_fkey', 'user_pc', 'component', ['gpu_id'], ['id'])
    op.create_foreign_key('user_pc_cpu_id_fkey', 'user_pc', 'component', ['cpu_id'], ['id'])
    op.create_foreign_key('user_pc_power_id_fkey', 'user_pc', 'component', ['power_id'], ['id'])
    op.create_foreign_key('user_pc_memory_id_fkey', 'user_pc', 'component', ['memory_id'], ['id'])
    op.alter_column('user_pc', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('user_pc_component')
    op.drop_table('ready_pc_component')
    op.drop_table('ready_pc')
    # ### end Alembic commands ###
