"""Таблица комплектующих

Revision ID: 9112e618d726
Revises: e3cca956d187
Create Date: 2024-04-15 22:27:09.309014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9112e618d726'
down_revision: Union[str, None] = 'e3cca956d187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pc_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('cpu', 'gpu', 'motherboard', 'ram', 'memory', 'power', 'cooler', 'case', name='component_types'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('descrition', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pc_id'], ['user_pc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('component')
    # ### end Alembic commands ###
