"""Component

Revision ID: f8f9c7f22032
Revises: 2b70845a724f
Create Date: 2024-05-17 00:50:26.149162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8f9c7f22032'
down_revision: Union[str, None] = '2b70845a724f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('component', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('component', 'price')
    # ### end Alembic commands ###
