"""test

Revision ID: f939325d29e4
Revises: 1fbb2f8be5fe
Create Date: 2024-04-16 23:33:05.350877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f939325d29e4'
down_revision: Union[str, None] = '1fbb2f8be5fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('component_pc_id_fkey', 'component', type_='foreignkey')
    op.drop_column('component', 'pc_id')
    op.add_column('user_pc', sa.Column('cpu', sa.Integer(), nullable=True))
    op.add_column('user_pc', sa.Column('gpu', sa.Integer(), nullable=True))
    op.add_column('user_pc', sa.Column('mb', sa.Integer(), nullable=True))
    op.add_column('user_pc', sa.Column('ram', sa.Integer(), nullable=True))
    op.add_column('user_pc', sa.Column('memory', sa.Integer(), nullable=True))
    op.add_column('user_pc', sa.Column('power', sa.Integer(), nullable=True))
    op.add_column('user_pc', sa.Column('cooler', sa.Integer(), nullable=True))
    op.add_column('user_pc', sa.Column('case', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_pc', 'component', ['case'], ['id'])
    op.create_foreign_key(None, 'user_pc', 'component', ['power'], ['id'])
    op.create_foreign_key(None, 'user_pc', 'component', ['cpu'], ['id'])
    op.create_foreign_key(None, 'user_pc', 'component', ['ram'], ['id'])
    op.create_foreign_key(None, 'user_pc', 'component', ['gpu'], ['id'])
    op.create_foreign_key(None, 'user_pc', 'component', ['memory'], ['id'])
    op.create_foreign_key(None, 'user_pc', 'component', ['mb'], ['id'])
    op.create_foreign_key(None, 'user_pc', 'component', ['cooler'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_pc', type_='foreignkey')
    op.drop_constraint(None, 'user_pc', type_='foreignkey')
    op.drop_constraint(None, 'user_pc', type_='foreignkey')
    op.drop_constraint(None, 'user_pc', type_='foreignkey')
    op.drop_constraint(None, 'user_pc', type_='foreignkey')
    op.drop_constraint(None, 'user_pc', type_='foreignkey')
    op.drop_constraint(None, 'user_pc', type_='foreignkey')
    op.drop_constraint(None, 'user_pc', type_='foreignkey')
    op.drop_column('user_pc', 'case')
    op.drop_column('user_pc', 'cooler')
    op.drop_column('user_pc', 'power')
    op.drop_column('user_pc', 'memory')
    op.drop_column('user_pc', 'ram')
    op.drop_column('user_pc', 'mb')
    op.drop_column('user_pc', 'gpu')
    op.drop_column('user_pc', 'cpu')
    op.add_column('component', sa.Column('pc_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('component_pc_id_fkey', 'component', 'user_pc', ['pc_id'], ['id'])
    # ### end Alembic commands ###
